// Définition des succès (refonte complète : ~50 succès en familles, paliers croissants).
// Chaque succès :
// - id unique, nom, emoji, description, famille (pour le regroupement visuel)
// - condition(etat) → true si débloqué
// - progres(etat) → { actuel, cible } pour la barre de progression
// - recompense :
//     { type: 'argent', montant }
//   | { type: 'ball', ball, quantite }
//   | { type: 'pierre', pierre, quantite }
//   | { type: 'bonus', stat: 'xp'|'argent', valeur }   (bonus PERMANENT, ex 0.05 = +5%)
// etat = { nbCaptures, nbShiny, nbVus, totalDex, nbVaincus, nbBoss, nbDresseurs, nbZones, nbSpeciaux }
//
// ÉQUILIBRAGE (rareté des récompenses) :
// - Master Ball UNIQUEMENT sur les 2 succès les plus durs du jeu (Pokédex complet + tous les dresseurs).
// - Toutes les autres récompenses (argent, super/hyper balls, pierres) revues à la baisse (~50%).

// Familles (ordre d'affichage + en-têtes du panneau).
export const FAMILLES_SUCCES = [
  { cle: 'captures',  nom: 'Captures',           emoji: '🎯' },
  { cle: 'dex',       nom: 'Pokédex',            emoji: '📖' },
  { cle: 'shiny',     nom: 'Chasse au Shiny',    emoji: '✨' },
  { cle: 'combats',   nom: 'Combats',            emoji: '⚔️' },
  { cle: 'boss',      nom: 'Boss de zone',       emoji: '👑' },
  { cle: 'zones',     nom: 'Exploration',        emoji: '🗺️' },
  { cle: 'arene',     nom: 'Arène',              emoji: '🏟️' },
  { cle: 'speciaux',  nom: 'Pokémon Spéciaux',   emoji: '🌟' },
]

export const SUCCES = [
  // ===================== CAPTURES =====================
  { id: 'capture_1', famille: 'captures', nom: 'Premier pas', emoji: '🎯',
    description: 'Capture ton premier Pokémon.',
    condition: (e) => e.nbCaptures >= 1, progres: (e) => ({ actuel: e.nbCaptures, cible: 1 }),
    recompense: { type: 'argent', montant: 50 } },
  { id: 'capture_25', famille: 'captures', nom: 'Apprenti dresseur', emoji: '📦',
    description: 'Capture 25 Pokémon.',
    condition: (e) => e.nbCaptures >= 25, progres: (e) => ({ actuel: e.nbCaptures, cible: 25 }),
    recompense: { type: 'ball', ball: 'super', quantite: 5 } },
  { id: 'capture_75', famille: 'captures', nom: 'Collectionneur', emoji: '📦',
    description: 'Capture 75 Pokémon.',
    condition: (e) => e.nbCaptures >= 75, progres: (e) => ({ actuel: e.nbCaptures, cible: 75 }),
    recompense: { type: 'ball', ball: 'hyper', quantite: 7 } },
  { id: 'capture_150', famille: 'captures', nom: 'Maître captureur', emoji: '🏅',
    description: 'Capture 150 Pokémon.',
    condition: (e) => e.nbCaptures >= 150, progres: (e) => ({ actuel: e.nbCaptures, cible: 150 }),
    recompense: { type: 'argent', montant: 2500 } },
  { id: 'capture_300', famille: 'captures', nom: 'Obsédé du Pokédex', emoji: '🎒',
    description: 'Capture 300 Pokémon.',
    condition: (e) => e.nbCaptures >= 300, progres: (e) => ({ actuel: e.nbCaptures, cible: 300 }),
    recompense: { type: 'pierre', pierre: 'moon-stone', quantite: 2 } },
  { id: 'capture_600', famille: 'captures', nom: 'Légende vivante', emoji: '👑',
    description: 'Capture 600 Pokémon.',
    condition: (e) => e.nbCaptures >= 600, progres: (e) => ({ actuel: e.nbCaptures, cible: 600 }),
    recompense: { type: 'bonus', stat: 'xp', valeur: 0.05 } },

  // ===================== POKÉDEX (espèces vues / %) =====================
  { id: 'dex_25', famille: 'dex', nom: 'Pokédex : 25 espèces', emoji: '📖',
    description: 'Enregistre 25 espèces différentes.',
    condition: (e) => e.nbVus >= 25, progres: (e) => ({ actuel: e.nbVus, cible: 25 }),
    recompense: { type: 'pierre', pierre: 'fire-stone', quantite: 1 } },
  { id: 'dex_75', famille: 'dex', nom: 'Pokédex : 75 espèces', emoji: '📖',
    description: 'Enregistre 75 espèces différentes.',
    condition: (e) => e.nbVus >= 75, progres: (e) => ({ actuel: e.nbVus, cible: 75 }),
    recompense: { type: 'pierre', pierre: 'water-stone', quantite: 2 } },
  { id: 'dex_150', famille: 'dex', nom: 'Pokédex : 150 espèces', emoji: '📖',
    description: 'Enregistre 150 espèces différentes.',
    condition: (e) => e.nbVus >= 150, progres: (e) => ({ actuel: e.nbVus, cible: 150 }),
    recompense: { type: 'argent', montant: 2000 } },
  { id: 'dex_quart', famille: 'dex', nom: 'Quart de chemin', emoji: '🗂️',
    description: 'Complète 25% du Pokédex.',
    condition: (e) => e.nbVus >= e.totalDex * 0.25, progres: (e) => ({ actuel: e.nbVus, cible: Math.round(e.totalDex * 0.25) }),
    recompense: { type: 'ball', ball: 'hyper', quantite: 3 } },
  { id: 'dex_moitie', famille: 'dex', nom: 'À mi-parcours', emoji: '🗂️',
    description: 'Complète 50% du Pokédex.',
    condition: (e) => e.nbVus >= e.totalDex * 0.5, progres: (e) => ({ actuel: e.nbVus, cible: Math.round(e.totalDex * 0.5) }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.05 } },
  { id: 'dex_complet', famille: 'dex', nom: 'Maître du Pokédex', emoji: '🏆',
    description: 'Complète 100% du Pokédex (1025 espèces).',
    condition: (e) => e.nbVus >= e.totalDex, progres: (e) => ({ actuel: e.nbVus, cible: e.totalDex }),
    recompense: { type: 'ball', ball: 'master', quantite: 1 } },

  // ===================== SHINIES =====================
  { id: 'shiny_1', famille: 'shiny', nom: 'Première brillance', emoji: '✨',
    description: 'Capture ton premier Pokémon shiny.',
    condition: (e) => e.nbShiny >= 1, progres: (e) => ({ actuel: e.nbShiny, cible: 1 }),
    recompense: { type: 'pierre', pierre: 'shiny-stone', quantite: 1 } },
  { id: 'shiny_5', famille: 'shiny', nom: 'Chasseur de shinies', emoji: '✨',
    description: 'Capture 5 Pokémon shiny.',
    condition: (e) => e.nbShiny >= 5, progres: (e) => ({ actuel: e.nbShiny, cible: 5 }),
    recompense: { type: 'argent', montant: 2500 } },
  { id: 'shiny_15', famille: 'shiny', nom: 'Collectionneur scintillant', emoji: '🌟',
    description: 'Capture 15 Pokémon shiny.',
    condition: (e) => e.nbShiny >= 15, progres: (e) => ({ actuel: e.nbShiny, cible: 15 }),
    recompense: { type: 'ball', ball: 'hyper', quantite: 5 } },
  { id: 'shiny_30', famille: 'shiny', nom: 'Aimant à shinies', emoji: '🌟',
    description: 'Capture 30 Pokémon shiny.',
    condition: (e) => e.nbShiny >= 30, progres: (e) => ({ actuel: e.nbShiny, cible: 30 }),
    recompense: { type: 'argent', montant: 7500 } },
  { id: 'shiny_60', famille: 'shiny', nom: 'Roi de la chasse', emoji: '👑',
    description: 'Capture 60 Pokémon shiny.',
    condition: (e) => e.nbShiny >= 60, progres: (e) => ({ actuel: e.nbShiny, cible: 60 }),
    recompense: { type: 'bonus', stat: 'xp', valeur: 0.05 } },
  { id: 'shiny_100', famille: 'shiny', nom: 'Maître du chromatique', emoji: '💎',
    description: 'Capture 100 Pokémon shiny.',
    condition: (e) => e.nbShiny >= 100, progres: (e) => ({ actuel: e.nbShiny, cible: 100 }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.10 } },

  // ===================== COMBATS =====================
  { id: 'combat_50', famille: 'combats', nom: 'Premiers combats', emoji: '⚔️',
    description: 'Gagne 50 combats.',
    condition: (e) => e.nbVaincus >= 50, progres: (e) => ({ actuel: e.nbVaincus, cible: 50 }),
    recompense: { type: 'ball', ball: 'super', quantite: 5 } },
  { id: 'combat_250', famille: 'combats', nom: 'Vétéran', emoji: '⚔️',
    description: 'Gagne 250 combats.',
    condition: (e) => e.nbVaincus >= 250, progres: (e) => ({ actuel: e.nbVaincus, cible: 250 }),
    recompense: { type: 'argent', montant: 1500 } },
  { id: 'combat_1000', famille: 'combats', nom: 'Machine de guerre', emoji: '🛡️',
    description: 'Gagne 1000 combats.',
    condition: (e) => e.nbVaincus >= 1000, progres: (e) => ({ actuel: e.nbVaincus, cible: 1000 }),
    recompense: { type: 'argent', montant: 8000 } },
  { id: 'combat_5000', famille: 'combats', nom: 'Inarrêtable', emoji: '🔥',
    description: 'Gagne 5000 combats.',
    condition: (e) => e.nbVaincus >= 5000, progres: (e) => ({ actuel: e.nbVaincus, cible: 5000 }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.05 } },
  { id: 'combat_20000', famille: 'combats', nom: 'Légende du combat', emoji: '⭐',
    description: 'Gagne 20 000 combats.',
    condition: (e) => e.nbVaincus >= 20000, progres: (e) => ({ actuel: e.nbVaincus, cible: 20000 }),
    recompense: { type: 'bonus', stat: 'xp', valeur: 0.10 } },

  // ===================== BOSS DE ZONE =====================
  { id: 'boss_1', famille: 'boss', nom: 'Tombeur de boss', emoji: '👑',
    description: 'Vaincs ton premier boss de zone.',
    condition: (e) => e.nbBoss >= 1, progres: (e) => ({ actuel: e.nbBoss, cible: 1 }),
    recompense: { type: 'argent', montant: 750 } },
  { id: 'boss_5', famille: 'boss', nom: 'Briseur de légendes', emoji: '👑',
    description: 'Vaincs 5 boss de zone.',
    condition: (e) => e.nbBoss >= 5, progres: (e) => ({ actuel: e.nbBoss, cible: 5 }),
    recompense: { type: 'pierre', pierre: 'dusk-stone', quantite: 2 } },
  { id: 'boss_15', famille: 'boss', nom: 'Chasseur de légendaires', emoji: '🐉',
    description: 'Vaincs 15 boss de zone.',
    condition: (e) => e.nbBoss >= 15, progres: (e) => ({ actuel: e.nbBoss, cible: 15 }),
    recompense: { type: 'ball', ball: 'hyper', quantite: 5 } },
  { id: 'boss_40', famille: 'boss', nom: 'Fléau des boss', emoji: '⚡',
    description: 'Vaincs 40 boss de zone.',
    condition: (e) => e.nbBoss >= 40, progres: (e) => ({ actuel: e.nbBoss, cible: 40 }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.05 } },
  { id: 'boss_75', famille: 'boss', nom: 'Souverain des zones', emoji: '👑',
    description: 'Vaincs 75 boss de zone.',
    condition: (e) => e.nbBoss >= 75, progres: (e) => ({ actuel: e.nbBoss, cible: 75 }),
    recompense: { type: 'bonus', stat: 'xp', valeur: 0.08 } },
  { id: 'boss_100', famille: 'boss', nom: 'Maître absolu', emoji: '🏆',
    description: 'Vaincs les 100 boss de zone.',
    condition: (e) => e.nbBoss >= 100, progres: (e) => ({ actuel: e.nbBoss, cible: 100 }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.10 } },

  // ===================== ZONES / EXPLORATION =====================
  { id: 'zone_5', famille: 'zones', nom: 'En route !', emoji: '🗺️',
    description: 'Débloque 5 zones.',
    condition: (e) => e.nbZones >= 5, progres: (e) => ({ actuel: e.nbZones, cible: 5 }),
    recompense: { type: 'ball', ball: 'super', quantite: 7 } },
  { id: 'zone_15', famille: 'zones', nom: 'Globe-trotter', emoji: '🧭',
    description: 'Débloque 15 zones.',
    condition: (e) => e.nbZones >= 15, progres: (e) => ({ actuel: e.nbZones, cible: 15 }),
    recompense: { type: 'argent', montant: 2000 } },
  { id: 'zone_40', famille: 'zones', nom: 'Explorateur chevronné', emoji: '🏔️',
    description: 'Débloque 40 zones.',
    condition: (e) => e.nbZones >= 40, progres: (e) => ({ actuel: e.nbZones, cible: 40 }),
    recompense: { type: 'pierre', pierre: 'sun-stone', quantite: 2 } },
  { id: 'zone_70', famille: 'zones', nom: 'Cartographe', emoji: '🗺️',
    description: 'Débloque 70 zones.',
    condition: (e) => e.nbZones >= 70, progres: (e) => ({ actuel: e.nbZones, cible: 70 }),
    recompense: { type: 'bonus', stat: 'xp', valeur: 0.05 } },
  { id: 'zone_100', famille: 'zones', nom: 'Bout du monde', emoji: '🌍',
    description: 'Débloque les 100 zones.',
    condition: (e) => e.nbZones >= 100, progres: (e) => ({ actuel: e.nbZones, cible: 100 }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.10 } },

  // ===================== ARÈNE =====================
  { id: 'arene_1', famille: 'arene', nom: 'Premier défi', emoji: '🏟️',
    description: 'Bats ton premier dresseur en Arène.',
    condition: (e) => e.nbDresseurs >= 1, progres: (e) => ({ actuel: e.nbDresseurs, cible: 1 }),
    recompense: { type: 'argent', montant: 500 } },
  { id: 'arene_10', famille: 'arene', nom: 'Habitué de l\'Arène', emoji: '🥊',
    description: 'Bats 10 dresseurs en Arène.',
    condition: (e) => e.nbDresseurs >= 10, progres: (e) => ({ actuel: e.nbDresseurs, cible: 10 }),
    recompense: { type: 'ball', ball: 'hyper', quantite: 10 } },
  { id: 'arene_25', famille: 'arene', nom: 'Combattant d\'élite', emoji: '🥋',
    description: 'Bats 25 dresseurs en Arène.',
    condition: (e) => e.nbDresseurs >= 25, progres: (e) => ({ actuel: e.nbDresseurs, cible: 25 }),
    recompense: { type: 'argent', montant: 5000 } },
  { id: 'arene_50', famille: 'arene', nom: 'Terreur de l\'Arène', emoji: '🏅',
    description: 'Bats 50 dresseurs en Arène.',
    condition: (e) => e.nbDresseurs >= 50, progres: (e) => ({ actuel: e.nbDresseurs, cible: 50 }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.05 } },
  { id: 'arene_75', famille: 'arene', nom: 'Grand Maître', emoji: '👑',
    description: 'Bats les 75 dresseurs de l\'Arène.',
    condition: (e) => e.nbDresseurs >= 75, progres: (e) => ({ actuel: e.nbDresseurs, cible: 75 }),
    recompense: { type: 'ball', ball: 'master', quantite: 1 } },

  // ===================== POKÉMON SPÉCIAUX =====================
  { id: 'special_1', famille: 'speciaux', nom: 'Forme légendaire', emoji: '🌟',
    description: 'Débloque ton premier Pokémon spécial (méga/forme).',
    condition: (e) => e.nbSpeciaux >= 1, progres: (e) => ({ actuel: e.nbSpeciaux, cible: 1 }),
    recompense: { type: 'argent', montant: 2500 } },
  { id: 'special_5', famille: 'speciaux', nom: 'Collectionneur de formes', emoji: '🌟',
    description: 'Débloque 5 Pokémon spéciaux.',
    condition: (e) => e.nbSpeciaux >= 5, progres: (e) => ({ actuel: e.nbSpeciaux, cible: 5 }),
    recompense: { type: 'ball', ball: 'hyper', quantite: 5 } },
  { id: 'special_10', famille: 'speciaux', nom: 'Chasseur de méga-évolutions', emoji: '💫',
    description: 'Débloque 10 Pokémon spéciaux.',
    condition: (e) => e.nbSpeciaux >= 10, progres: (e) => ({ actuel: e.nbSpeciaux, cible: 10 }),
    recompense: { type: 'bonus', stat: 'xp', valeur: 0.05 } },
  { id: 'special_15', famille: 'speciaux', nom: 'Panthéon complet', emoji: '🏆',
    description: 'Débloque les 15 Pokémon spéciaux.',
    condition: (e) => e.nbSpeciaux >= 15, progres: (e) => ({ actuel: e.nbSpeciaux, cible: 15 }),
    recompense: { type: 'bonus', stat: 'argent', valeur: 0.15 } },
]